[[redirects]]
force = true
from = '/techy-blog/api/'
status = 200
to = 'https://blog-api-server-26kg.onrender.com/'

[[redirects]]
from = '/*'
status = 200
to = '/index.html'

[build]
command = 'npm run build'
publish = 'dist'