[[redirects]]
force = true
from = '/techy-blog/api/*'
status = 200
to = 'https://blog-api-server-production-0d8e.up.railway.app/techy-blog/api/:splat'

[[redirects]]
from = '/*'
status = 200
to = '/index.html'